Qualytics/userguide

- docs/security/security-page.md
Updated security page bug where the title was being used in the TOC
> Updated security-page.md bug

- docs/index.md
Changed the loom video in index.md file
> Fixed iframe on index.md for new loom video

- docs/changelog.md
- docs/glossary.md
- docs/quick-start-guide.md
- mkdocs.yml
Cleaned up glossary (extra space affected formatting for TOC)
Cleaned up getting started (broken links and images due to misconfiguration on local)
> Cleaned up User Guide issues from earlier

- docs/tags/what-is-a-tag.md
updated tags.md
accidenntally deleted the sections about Applying a Tag and Tag Inheritance
> updated tags.md

- docs/changelog.md
added release notes to changelog.md
> updated changelog.md

- docs/changelog.md
> update changelog.md 

- docs/changelog.md
Updated changelog.md with 2023.07.29 entry
> Updated changelog.md with 2023.07.29 entry

- docs/changelog.md
> Update changelog.md 2023.07.29

- contributing/check-content-template-guide.md
- mkdocs.yml
This PR includes a new markdown file to serve as a template guide for creating new Checks.
Also, some minor adjustments were made to the `mkdocs` file.
> Create a Check Template Guide for Contributions and Few Tweaks 

- docs/checks/aggregation-comparison-check.md
This PR updates the example section in the Aggregation Comparison User Guide and includes practical input usage demonstrations of valid aggregations.
The revision includes more realistic and practical examples that demonstrate the use of aggregation comparisons in a clearer and more applicable way. The changes aim to enhance the understanding and usability of the guide for users.
> Update Example Section in Aggregation Comparison Page

- docs/identifiers/what-is-an-identifier.md
1. Added a brief description of what is an identifier:
2. Moved the managing an identifier after
3. Explaining better the incremental strategy with a new table of options
4. Explained better Why DFS don't need to setup the identifiers.
5. Added example with sample data (table) + explanation of incremental strategy with flowchart and SQL
6. Explaining better the Partition Field with a new info + warning boxes:
7. Added example with sample data (table) + explanation of partition fieldwith flowchart and SQL
> Refactor What is an identifier page

- docs/upgrades/qualytics-single-tenant-instance.md
- mkdocs.yml
1. Added the following sections:
```
What is in this chart?
How should I use this chart?
1. Create a CNCF compliant cluster
Node Requirements
Docker Registry Secrets
2. Update values.yaml with appropriate values
3. Deploy Qualytics to your cluster
4. Register your deployment's web application
Upgrade Qualytics Helm chart
Update Qualytics Helm Chart:
Upgrade Qualytics Helm Chart:
Monitor Update Progress:
Verify Update
Can I run a fully "air-gapped" deployment?
```
> Added section related to install and upgrade section for on-prem deployments

- docs/datastores/what-is-a-dfs-datastore.md
- docs/datastores/what-is-a-jdbc-datastore.md
- docs/dfs-globbing/how-dfs-filename-globbing-works.md
- mkdocs.yml
1. Improved the section of datastores. Now we have 1 page for What is a JDBC datastore and 1 page for What is a DFS datastore. Also, each section will have a Create Datastore page if it refers to JDBC or DFS
2. On `What is a DFS datastore` I added some sections, here are:
```
Multi-Token Filename Globbing and Container Formation:
Use Folders for Precise File Grouping
How to Use Folders for Shared Schema:
1. Create a Folder:
2. Place Related Files in the Folder:
3. Repeat for Each Schema:
4. Naming Conventions:
Flowchart: Using Folders for Shared Schema
Use Filename Conventions for Posix Globs:
How to Use Filename Conventions for Posix Globs
1. Follow Clear Filename Conventions:
2. Upload or Move Files:
3. System Analysis:
Flowchart: Using Folders for Filename Conventions
Why not manually …
```
> Improved and added a section related to dfs globbing

- docs/container/container.md
- docs/container/export-metadata.md
- docs/container/overview-of-grouping.md
- docs/container/overview-of-identifiers.md
- mkdocs.yml
1. Reworked on identifiers section to containers
2. Added new grouping page for containers
> Reworked on identifiers and added new grouping section

- docs/cli/overview-of-qualytics-cli.md
Changed verbiage for check operation status. Updated to be accurate.
> updated verbiage to be accurate

- docs/settings/security/security-page.md
> Added User Roles and Permissions section

- docs/datastores/bigquery.md
> Updated BQ permissions read role

- docs/datastores/bigquery.md
> Update bq permissions

- docs/changelog.md
> Add release notes for RC 2024.05.22

- docs/cli/overview-of-qualytics-cli.md
> Added python examples to CLI

- docs/changelog.md
- docs/checks/aggregation-comparison-check.md
- docs/checks/equal-to-field-check.md
- docs/components/comparators/string.md
> Add release notes for RC 2024.06.04

- docs/anomalies/anomaly-details.md
- docs/datastores/amazon-s3.md
- docs/datastores/azure-blob-storage.md
- docs/datastores/azure-datalake-storage.md
- docs/datastores/bigquery.md
- docs/datastores/databricks.md
- docs/datastores/db2.md
- docs/datastores/google-cloud-storage.md
- docs/datastores/hive.md
- docs/datastores/maria-db.md
- docs/datastores/microsoft-sql-server.md
- docs/datastores/mysql.md
- docs/datastores/oracle.md
- docs/datastores/postgresql.md
- docs/datastores/presto.md
- docs/datastores/redshift.md
- docs/datastores/snowflake.md
- docs/datastores/synapse.md
- docs/datastores/timescale-db.md
- docs/datastores/trino.md
- docs/enrichment/associate-enrichment-datastore.md
- docs/operations/catalog.md
- docs/operations/external-scan.md
- docs/operations/profile.md
- docs/operations/scan.md
> Enhanced userguide with payload examples

- docs/anomalies/anomaly-details.md
- docs/datastores/amazon-s3.md
- docs/datastores/azure-blob-storage.md
- docs/datastores/azure-datalake-storage.md
- docs/datastores/bigquery.md
- docs/datastores/databricks.md
- docs/datastores/db2.md
- docs/datastores/google-cloud-storage.md
- docs/datastores/hive.md
- docs/datastores/maria-db.md
- docs/datastores/microsoft-sql-server.md
- docs/datastores/mysql.md
- docs/datastores/oracle.md
- docs/datastores/postgresql.md
- docs/datastores/presto.md
- docs/datastores/redshift.md
- docs/datastores/snowflake.md
- docs/datastores/synapse.md
- docs/datastores/timescale-db.md
- docs/datastores/trino.md
- docs/enrichment/associate-enrichment-datastore.md
- docs/enrichment/overview-of-an-enrichment-datastore.md
- docs/operations/catalog.md
- docs/operations/external-scan.md
- docs/operations/profile.md
- docs/operations/scan.md
> SC-17015: Add endpoint examples for enrichment tables

- docs/enrichment/overview-of-an-enrichment-datastore.md
> Add difference between source records and remediation tables + payload examples

- docs/changelog.md
Update `deprecation` to `warning`
> fix: update release notes

- docs/changelog.md
- Global Search
- We are thrilled to introduce the “Global Search” feature into Qualytics! This enhancement is designed to streamline the search across the most crucial assets: Datastores, Containers, and Fields. It provides quick and precise search results, significantly improving navigation and user interaction.
- Navigation Update: To integrate the new global search bar seamlessly, we have relocated the main menu icons to the left side of the interface. This adjustment ensures a smoother user experience.
- Teradata Connector
- We’ve expanded our connectivity options by supporting a new connection with Teradata. This enhancement allows users to connect and interact with Teradata databases directly from Qualytics, facilitating more diverse data management capabilities.
- Snowflake …
> Add release notes for RC 2024.07.19

- docs/changelog.md
- Introducing Event Bus for Extended Auto-Sync with Data Catalog Integrations
- We are excited to expand our auto-sync capabilities with data catalog integrations by implementing an event bus pattern.
- Added functionality to delete any DQ values that do not meet important checks.
- Included support for a WARNING status in the Alation Data Health tab for checks that have not been asserted yet.
- Add Autocomplete to the Notification Form
- Improved the notification message form by implementing autocomplete. Users can now easily include internal variables when crafting custom messages, streamlining the message creation process.
- Redesign the Analytics Engine Functions
- The functions are now accessible through a menu, which displays the icon and full functionality.
- Added a modal to alert …
> Add release notes for RC 2024.07.26

- docs/changelog.md
- Introducing Field Count to the datastore overview
- This enhancement allows users to easily view the total number of fields present in a datastore across all containers.
- Search Template
- Added a check filter to the templates page.
- Added a template filter to the checks page in the datastore context and explore.
- Driver Free Memory
- Added driver free memory information on the Health Page.
- Anomalous Record Count to the Anomaly Sidebar Card
- Added the anomalous record count information to the anomaly sidebar card located under the Scan Results dialog.
- Enhanced write performance on scan operations with enrichment and relaxed hard timeouts.
- Updated Azure Blob Storage connector to use TLS encrypted access by default.
- Overview Tab is not refreshing asset details automatically.
- …
> Add release notes for RC 2024.07.31

- docs/add-datastores/hive.md
- docs/add-datastores/maria-db.md
- docs/add-datastores/presto.md
- docs/add-datastores/qfs.md
- docs/add-datastores/synapse.md
- docs/add-datastores/trino.md
- docs/enrichment/overview-of-an-enrichment-datastore.md
- docs/glossary.md
- docs/technical-quick-start-guide.md
https://app.shortcut.com/qualytics/story/17658
This Pull Request will fix some broken links
1. https://userguide.qualytics.io/technical-quick-start-guide/
2. https://userguide.qualytics.io/glossary/
3. https://userguide.qualytics.io/add-datastores/hive/
4. https://userguide.qualytics.io/add-datastores/maria-db/
5. https://userguide.qualytics.io/add-datastores/presto/
6. https://userguide.qualytics.io/add-datastores/synapse/
7. https://userguide.qualytics.io/add-datastores/trino/
8. https://userguide.qualytics.io/enrichment/overview-of-an-enrichment-datastore/
> SC-17658: Fix the User Guide broken links

- docs/add-datastores/maria-db.md
https://app.shortcut.com/qualytics/story/17658
This Pull Request will fix some broken links
1. https://userguide.qualytics.io/add-datastores/maria-db/
> SC-17658: Fix Maria DB broken link

- .github/pull_request_template.md
https://app.shortcut.com/qualytics/story/17713
This Pull Request will add a PR template to standardize and consistent descriptions
> SC-17713: Add PR Template

- .github/pull_request_template.md
> chore: removing content

- docs/changelog.md
This PR includes Release notes for RC 2024.08.10
- feat(changelog): Add release notes for RC 2024.08.10
> SC-17756: Add release notes for RC 2024.08.10

- docs/changelog.md
This PR includes Release notes for RC 2024.08.19
- feat(changelog): Add release notes for RC 2024.08.19
> SC-17863: Add release notes for RC 2024.08.19

- docs/checks/satisfies-expression-check.md
This PR includes the addition of the "Use Case" section to the "Satisfies Expression" file
- **<feat1>Added "Use Case" Section**: <optional description>Introduced practical examples demonstrating how to use Satisfies Expressions effectively in different scenarios.
https://github.com/user-attachments/assets/26212acc-e50d-4698-87c8-3b1d53c40c2f
> Added Use Case section to Satisfies Expression file

- docs/source-datastore/profile.md
This PR includes corrections to typos found throughout the documentation and updates to the API Payload Examples to ensure accuracy and clarity.
- **<feat1>Typo Corrections**: <optional description>Fix the typo for "Catalog" and change it to "Profile" 
- **<feat2>Updated API Payload Examples** <optional description>
> Fixed the typos and updated API example section in "Profile" file

- docs/changelog.md
This PR includes Release notes for RC 2024.08.30
- feat(changelog): Add release notes for RC 2024.08.30
> SC-18002: Add release notes for RC 2024.08.30

- docs/changelog.md
This PR includes Release notes for RC 2024.09.06
- feat(changelog): Add release notes for RC 2024.09.06
> SC-18140: Add release notes for RC 2024.09.06

- docs/changelog.md
This PR includes Release notes for RC 2024.09.10
- feat(changelog): Add release notes for RC 2024.09.10
> SC-18140: Add release notes for RC 2024.09.10

- docs/changelog.md
This PR includes Release notes for RC 2024.09.14
- feat(changelog): Add release notes for RC 2024.09.13
- fix(changelog): update the release date
> SC-18242: Add release notes for RC 2024.09.14

- docs/changelog.md
This PR includes Release notes for RC 2024.09.25
- feat(changelog): Add release notes for RC2024.09.25
https://github.com/user-attachments/assets/5108f724-4116-44ed-8e83-5242d5d04a6d
> SC-18242: Add release notes for RC 2024.09.25

- docs/add-datastores/athena.md
This PR updates the content for the "Athena Datastore" file to ensure the documentation reflects the latest features and improvements. The revisions provide clearer explanations and align the content with the current functionality of Athena Datastore.
- Updated<feat1>: <optional description>Content
> SC-18225: Update  content for "Athena Datastore" file

- docs/settings/integrations/overview.md
This PR addresses and resolves all broken links in the Integration Overview page to ensure smoother navigation and improved user experience. By fixing these broken links, users will have seamless access to all relevant resources and documentation.
- <feat1>Updated: <optional description>Fixed broken links
> SC-18420: Updated broken links in the Integration Overview

- docs/changelog.md
This PR includes Release notes for RC 2024.10.04
- feat(changelog): Add release notes for RC 2024.10.04
> SC-18500: Release 2024.10.04

- docs/settings/security/teams-and-permissions.md
This PR includes the permission modifications for public team admin users can now modify Read and Write permissions.
- Updated<feat1>: <optional description>Content
> SC-18591: Added a note for public team

- docs/changelog.md
This PR includes Release notes for RC 2024.10.23
- docs(changelog): Add release notes for RC 2024.10.23
- docs(changelog): update relase notes
- style(changelog): add spacement
> SC-18735: Release 2024.10.23

- docs/container/computed-tables-and-files.md
This PR includes fixes for the broken "select-computed-table" image in both light and dark mode.
- **<feat1>Fixed image in light mode**: <optional description>Replaced the broken "select-computed-table" image for light mode.
- **<feat2>Fixed image in dark mode:**: <optional description>Replaced the broken "select-computed-table" image for dark mode.
> SC: 18596 Fixed the broken image "select-computed-table"

- docs/changelog.md
This PR includes Release notes for RC 2024.11.01
- docs(changelog): Add release notes for RC 2024.11.01
> docs(changelog): Add release notes for RC 2024.11.01

- docs/checks/volumetric-check.md
This PR includes the hyperlink "Scan Operation" in the volumetric check
- <feat1>Hyperlink **"Scan Operation"** in volumetric check <optional description>
> SC-18754: Hyperlink "Scan Operation" in volumetric check

- docs/technical-quick-start-guide.md
This PR includes fixing the broken links in the "Technical quick start guide"
- **<feat1>fix broken links** <optional description>
> SC-18754: Technical quick start guide File

- mkdocs.yml
This PR reorganizes the Data Quality Checks sections to facilitate easier navigation and sharing.
- Changes<feat1>: Reorganize the data quality checks sections.<optional description>
> Sc-18895: Reorganize the data quality check sections for intuitive flow.

- docs/changelog.md
This PR includes Release notes for RC 2024.11.12
- docs(changelog): Add release notes for RC 2024.11.12
- docs(changelog): update release notes
> SC-18896: Release 2024.11.12

- docs/checks/overview-of-a-check.md
- docs/checks/rule-types-overview.md
- mkdocs.yml
This PR adds a new "Rule Types Overview" section for a quick, consolidated view of all rule types.
- Add<feat1>: Rule Types Overview Section<optional description>
> Sc-18895: Add the "Rule Types Overview" section.

- docs/notifications/notification-services/pagerduty.md
This PR updates the image path for the PagerDuty file. Previously, the incorrect path caused warnings whenever viewed in VS Code. The image path is now adjusted to accurately locate the file without triggering warnings.
- Updated<feat1>: Image Path<optional description>
> Sc-18868: Update "PagerDuty" file.

- docs/weight/weighting.md
- mkdocs.yml
This PR added new section weight mechanism in userguide.
- Added<feat1>: Content<optional description>
> Sc-18886: Add "Weight Mechanishm" document.

- docs/changelog.md
This PR includes Release notes for RC 2024.12.11
- docs(changelog): Add release notes for RC 2024.12.11
> SC-19167: Release 2024.12.11

- docs/add-datastores/databricks.md
This PR includes changes to correct some numbers were displaying in a blue font style.
-Updated: Content
> Sc-19111: Update "Databricks" file.

- docs/add-datastores/mysql.md
Overview
This PR includes changes to correct some numbers were displaying in a blue font style.
Key Changes
Updated: Content
> Sc-19111: Update "MySQL" file.

- docs/add-datastores/redshift.md
Overview
This PR includes changes to correct some numbers were displaying in a blue font style.
Key Changes
Updated: Content
> Sc-19111:Update "Redshift" userguide.

- docs/changelog.md
This PR includes Release notes for RC 2024.12.23
- docs(changelog): Add release notes for RC 2024.12.23
> QUA-180: Release 2024.12.23

- docs/add-datastores/snowflake.md
Overview
This PR includes changes to correct some numbers were displaying in a blue font style.
Key Changes
Updated: Content
> Sc-19111:Update "Snowflake" userguide.

- docs/checks/overview-of-a-check.md
This PR fixed the broken link.
- Fix<feat1>: Link<optional description>
> Sc-19111: Fix Broken Link in "Checks Overview" File.

- docs/add-datastores/databricks.md
This PR fixed the image links
- Fixed<feat1>: Links<optional description>
> Fix the image link in "Databricks" file.

- docs/observability/observability.md
This PR fix the broken screenshots links.
- Fix<feat1>: Links<optional description>
> Qua-156: Update "Observability" File.

- docs/explore/overview-of-explore.md
This PR update broken links.
- Fix<feat1>: Links<optional description>
> Qua-156: Fix the broken links in "Overview" file

- docs/changelog.md
This PR includes Release notes for RC 2025.01.16
- docs(changelog): Add release notes for RC 2025.01.16
> QUA-226: RC 2025.01.16

- docs/changelog.md
This PR includes Release notes for RC 2025.01.20
- docs(changelog): Add release notes for RC 2025.01.20
> QUA-266: RC 2025.01.20

- docs/quick-start-guide.md
This PR fix the broken links
- Add<feat1>: Links<optional description>
> Qua-156: Update quick start guide in user guide

- docs/changelog.md
This PR includes Release notes for RC 2025.01.24
> QUA-281: RC 2025.01.24

- docs/container/container.md
This PR includes updated content and add new feature freshness as per the latest release.
> Qua:156- Update "Container Overview" userguide to add new feature freshness.

- docs/source-datastore/associate-enrichment-datastore.md
- Update<feat1>: Content<optional description>
> Qua-246: Update "Link Enrichment Datastore" File .

- docs/changelog.md
This PR includes Release notes for RC 2025.01.31
> QUA-306: RC 2025.01.31

- docs/changelog.md
- docs/glossary.md
Fixed broken links on changelog and glossary files
- fix(glossary): fixed datastore overview and Quality Score broken links
- fix(changelog): fixed explore and metric check broken link
> QUA-318: Warning messages from user guide project

- docs/connections/overview-of-a-connection.md
This PR fixes the broken image links.
- Fix<feat1>: Link<optional description>
> QUA-318: Update "Connection Overview" Document.

- docs/add-datastores/synapse.md
This PR fixes the broken image link.
- Fix<feat1>: Link<optional description>
> Qua318: Update "Synapse" userguide .

- docs/explore/overview-of-explore.md
This PR fixed the broken links.
- Fix<feat1>: Links<optional description>
> Qua326: Fix the broken link on "Explore" userguide.

- docs/checks/overview-of-a-check.md
This PR fixed the broken links.
- Fix<feat1>: Links <optional description>
> Qua326: Fix "Checks Overview" File Broken Links.

- docs/enrichment/overview-of-an-enrichment-datastore.md
This PR fixed the broken link.
- Fix<feat1>: Link<optional description>
> Qua326: Fix the broken Link on "Enrichment Datastore Overview File".

- docs/changelog.md
This PR includes Release notes for RC 2025.02.13
> QUA-336: RC2025.02.13

- docs/web-app.md
This PR includes the addition of the System Theme option in Qualytics, allowing the application to automatically switch between dark and light modes based on the user's system settings.
- **<feat1>Added System Theme support**: <optional description>Qualytics now adapts to the user's system theme, switching between dark and light mode automatically.
> QUA-341: Updated the theam section as per the latest release

- docs/enrichment-support/enrichment-support-datastores.md
- mkdocs.yml
This PR includes a document enrichment support datastores.
- Add<feat1>: Content<optional description>
> Qua372: Create a Document "Enrichment Support Datastores".

- docs/changelog.md
This PR includes Release notes for RC 2025.02.26
-  docs(changelog): add release notes
> QUA-375: RC2025.02.26

- docs/enrichment-support/enrichment-support-datastores.md
- mkdocs.yml
This PR updates the links as requested.
- Updated<feat1>: Links<optional description>
> QUA-372: Update "Enrichment Support Datastores" File.

- docs/changelog.md
This PR includes Release notes for RC 2025.03.05
- docs(changelog): removing isReplicaOf topic
> QUA-402 RC.2025.03.05

- docs/observability/observability.md
This PR adds a new info section to metrics to show minimum measurements required to render a chart.
- Add<feat1>: Content<optional description>
> QUA-412:  Update "Observability" File .

- mkdocs.yml
- requirements.txt
This PR includes...
- **<feat1>**: <optional description>
- **<feat2>**: <optional description>
> fix inbound link

- docs/changelog.md
This PR includes Release notes for RC 2025.03.17
- fix(changelog): remove some content and remove a topic
> QUA-422 RC.2025.03.17

- docs/observability/observability.md
This PR includes...
- fix(observability): add percentage change required number of measurement
> Fix: Observability measurement chart

- docs/changelog.md
This PR includes Release notes for RC 2025.03.21
> QUA-442: RC.2025.03.23

- docs/changelog.md
- docs/container/computed-tables-and-files.md
- Updated<feat1>: Content <optional description>
> QUA-370: Update "Computed Tables and Files" file.

- docs/settings/catalog-integrations/external-tag-propagation.md
- Updated<feat1>: Content <optional description>
> QUA-370: Update "External Tag Propagation" file.

- docs/checks/overview-of-a-check.md
- Updated<feat1>: Content <optional description>
> QUA-370: Update "Checks Overview" file.

- docs/enrichment/overview-of-an-enrichment-datastore.md
This PR includes updated content as per the latest release.
- Updated: Content<optional description>
> Qua-451: Update "Enrichment Datastore Overview File" as per the latest release.

- docs/source-datastore/scan.md
This PR includes updated content as per the latest release.
> QUA-451: Update "Scan Operation" File as per the latest release.

- docs/changelog.md
This PR includes Release notes for RC 2025.4.5
- chore: update the release date
> QUA-477: RC.2025.4.5

- docs/changelog.md
This PR includes Release notes for RC 2025.4.11
- fix(changelog): update anomalies topic
> QUA-504: RC.2025.4.11

- docs/container/export-operation.md
> Qua475: Update "Export Operation" file.

- docs/enrichment/overview-of-an-enrichment-datastore.md
> QUA-475: Update "Enrichment Datastore Overview" file.

- docs/changelog.md
This PR includes Release notes for RC 2025.4.24
- fix(changelog): update scan operation and api changes topic
> QUA-524: RC.2025.4.24

- docs/changelog.md
This PR includes Release notes for RC 2025.5.5
> QUA-554: RC.2025.5.5

- docs/enrichment/overview-of-an-enrichment-datastore.md
Updates check_metrics table from enrichment datastores section with the assertion_result and assertion_details
> Update check metrics table

- docs/changelog.md
This PR includes Release notes for RC 2025.5.9
> QUA-554: RC.2025.5.9

- docs/changelog.md
This PR includes Release notes for RC 2025.5.16
- fix(changelog): resume the release notes
> QUA-590: RC.2025.5.16

- docs/changelog.md
This PR includes Release notes for RC 2025.5.23
- docs(changelog): update the release date
- docs(changelog): added the rerun section
- docs(changelog): fixed misspelled word
> QUA-603: RC.2025.5.23

- docs/add-datastores/qfs.md
- Updated: Content<optional description>
> QUA-605: Fix typos in "Qualytics File System" userguide.

- docs/add-datastores/timescale-db.md
- Updated: Content<optional description>
> QUA-605: Fix typos in "TimescaleDB" userguide.

- docs/add-datastores/teradata.md
> Qua-605 Update Teradata userguide.

- docs/checks/field-count-check.md
This PR fixed misspelled words in user guides
> QUA-605: Update "Field Count Check" userguide.

- docs/add-datastores/maria-db.md
This PR fixes misspelled words in the user guide.
> QUA-605: Update"Maria DB" userguide.

- docs/add-datastores/mysql.md
- docs/observability/observability.md
> Qua-605: Fix "Observability" userguide.

- docs/container/manage-tables-and-files.md
> QUA-605: Update "Manage Tables and Files" userguides

- docs/checks/apply-check-template-for-quality-checks.md
> QUA:605-Update "Apply Check Template For Quality Checks" userguide.

- docs/add-datastores/snowflake.md
> QUA:605-Fix "Snowflake" userguide.

- docs/settings/tokens/overview-of-tokens.md
This PR fixed the misspelled words.
> QUA:605- Update "Token" userguide.

- docs/add-datastores/postgresql.md
This PR fixed the misspelled words.
> QUA:605- Update "PostgreSQL" userguide.

- docs/source-datastore/scan.md
This PR updated the content as per the latest release.
> QUA-627: Update "Scan Operation" file as per the latest release.

- docs/quality-scores/what-are-quality-scores.md
This PR includes...
- **<feat1>**: <optional description>
- **<feat2>**: <optional description>
> Add details to quality score writeup

- docs/changelog.md
This PR includes Release notes for v2025.6.20
> QUA-656: v2025.6.20

- docs/observability/observability.md
> QUA-605: Fix typos in "Observability" userguide.

- docs/changelog.md
This PR includes Release notes for v2025.7.18
- docs(changelog): update release notes
> QUA-724:  v2025.7.18

- docs/changelog.md
This PR includes Release notes for v2025.7.28
> QUA-770: v2025.7.28

- docs/404.md
This PR adds a 404 error page that displays when users attempt to navigate to non-existent routes
How to test: type any address in browser url that does not exist
According to the documentation we can only test in production.
https://www.mkdocs.org/user-guide/deploying-your-docs/#404-pages
feat(404): create and customize the 404 error page in User Guide.
> QUA-817: Not found page - User Guide

- docs/404.md
- mkdocs.yml
This PR updates the `site_url` property in mkdocs.yml to use the production url
- fix: update `site_url` property
> QUA-817: Not found page user guide

- docs/add-datastores/db2.md
This PR fixes the content as per the suggestions.
- **Fix**: Content<optional description>
> QUA-835: Update "DB2" userguide as per the suggestions.

- docs/404.md
- overrides/404.html
This PR creates a custom HTML 404 error page with improved design and user experience, replacing the basic "404 - Page not Found" message.
- Created custom 404 HTML page: Built a fully designed 404 error page with enhanced visual elements
- Improved user experience: Replaced plain text error with a user-friendly design that better guides users when they encounter missing pages
> QUA-817: Add 404 in html language

- docs/changelog.md
This PR includes Release notes for v2025.9.4
> QUA-911: v2025.9.4

- docs/enrichment-support/supported-enrichment-datastores.md
This PR update the userguide as per the suggestion.
- **Updated**: Content
> QUA-1007: Update "Supported Enrichment Datastores" userguide.

- docs/quality-scores/what-are-quality-scores.md
- docs/stylesheets/extra.css
Rewrite to reflect upcoming changes to scoring algorithm and for clarity & transparency.
> QUA-669: Rewrite quality scores for pending updates to algo and clarity
